### PR TITLE
Port tests over to GitHub Actions

### PR DESCRIPTION
**Pull request by neko314**
Set up GitHub Actions to run tests to check the PRs on GitHub.

## Description

I add YAML file to define workflow.

## Related Issue
#1685

## Motivation and Context

CI will help maintainer, contributors and users of CodeTriage to know the code work well, or alert soon when something is broken.  

## How Has This Been Tested?
I created the same PR to another forked repo ( https://github.com/gregmolnar/CodeTriage/pull/1 ), and run CI.
GitHub actions are triggered by pushing, and all jobs are success.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by gregmolnar** [comment]
@schneems I think you need to allow the checks to be run.

**Comment by neko314** [comment]
When I gain permission to run CI, it's found that CI fails on this PR https://github.com/gregmolnar/CodeTriage/pull/1 with @gregmolnar.
I need keep trying to accomplish set up. @gregmolnar will help me in need. Thank you
Anyway please allow the checks to be run.
This PR is open but not be finished. I'll mention when I finish it.

**Comment by schneems** [comment]
This is really exciting. Thank you for working on this! 

I'm not actually sure how to do that. I don't have any options in the UI. I think because there's not an existing GitHub action in the project, it's not triggering for you to add one. 

image

I see two options for moving forward: I can just merge this as is, and then you can fix it up if there are any errors or bugs. Alternatively, I could merge in an empty (or close to empty) GitHub action and see if that allows me to approve your CI run.  The downside of that option is it would probably result in merge conflicts for you.

I don't know if @deepakmahakale has some suggestions or ideas.

**Comment by neko314** [comment]
@schneems 

> I'm not actually sure how to do that. I don't have any options in the UI. I think because there's not an existing GitHub action in the project, it's not triggering for you to add one.

Do you see 'settings' tab on this repo page? 
You might be change any setting at `Settings > Actions > general > Fork pull request workflows from outside collaborators` . (Maybe, I just guess.)
image

> I can just merge this as is, and then you can fix it up if there are any errors or bugs.

I agree this way. If you so, I'll the commits get into one before you merge.
I already know all tests pass with Ruby 3.0 and 3.1 but some fails with 2.7 like [this](https://github.com/gregmolnar/CodeTriage/actions/runs/3261636379/jobs/5356978455). I think this failures are because of keyword arguments. I haven't fixed and don't know how to fix it yet but I'll keep going on.

**Comment by deepakmahakale** [comment]
Yes, @neko314 is correct. 
Found this article that says the same - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories

> By default, all first-time contributors require approval to run workflows.

**Comment by schneems** [comment]
> I already know all tests pass with Ruby 3.0 and 3.1 but some fails with 2.7

We can bump the minimum Ruby version in the Gemfile.lock instead. I don’t need to support running this under 2.7.

The ruby versions are flexible to make testing with newer Ruby versions easier. It really only needs to run on the Ruby version in the Gemfile.lock

**Comment by gregmolnar** [comment]
@schneems once Ruby 2.7 is removed from the test matrix, you can just merge the PR and the checks will run.

**Comment by neko314** [comment]
Thanks everyone!

I'll remove 2.7 from matrix, beautify commits, then this PR will actually be almost accomplished.

**Comment by neko314** [comment]
> I'll remove 2.7 from matrix, beautify commits, then this PR will actually be almost accomplished.

I've done them and I reviewed these changes by my self.
Please review this PR again. Thank you in advance.

**Comment by schneems** [comment]
Thank you for your work here! Merging in 🚀

**Comment by schneems** [comment]
Btw looks like tests are firing just fine for me. Thanks for your work!

**Pull request merged**
