### PR TITLE
Don't count things we don't have to

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by nateberkopec** [comment]
I looked at this a bunch, I wonder why will_paginate doesn't just pick that up automatically.

**Comment by schneems** [comment]
idK could be a good PR to kaminari or will paginate

**Comment by schneems** [comment]
Turns out this PR did nothing. That Option in will paginate does nothing

**Comment by grillermo** [comment]
This would be really useful i get double queries and double response time due to this to the point that i disable the counter in some pretty heavily requested views.

**Comment by nateberkopec** [comment]
I feel like there's something we don't know about pagination and AR, because kaminari has weird logic when it comes to this as well. :|

**Comment by schneems** [comment]
I can switch to "next page" without the numbers style of pagination to avoid the count. I'm not sure if I can pass in total count https://github.com/kaminari/kaminari/pull/681#issuecomment-258727907

Or I could replace with another totally different pagination query scheme.

**Pull request merged**
