### PR TITLE
Fix warnings from Rails 5

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Mime type related warnings will be fixed by https://github.com/schneems/maildown/pull/18

**Comment by schneems** [comment]
I'm good with this. You want to bump the maildown version on this branch?

**Comment by prathamesh-sonpatki** [comment]
@schneems Done

**Comment by prathamesh-sonpatki** [comment]
When I run tests locally using `bin/rails t` they get run twice - https://gist.github.com/prathamesh-sonpatki/d15ce1fcafb097986aef

Need to investigate why it is happening.

**Comment by prathamesh-sonpatki** [comment]
Also bumped `dotenv-rails`. They released Rails 5 compatible version.

**Comment by schneems** [comment]
Great, merge at will

**Pull request merged**
