### PR TITLE
updating gems

### PR DESCRIPTION
**Pull request by lostapathy**
This is a stab at updating some of the gems in the gemfile, mostly those that seemed like a safe/easy upgrade.

I wanted to PR my progress so far on this to keep it manageable, but I can keep working through updates on other packages once this much has landed.

### CODE REVIEW

**Comment by schneems** [comment]
Thanks!

**Comment by Schwad** [comment]
@schneems is this fella ready to be closed now that it's merged or is it still hanging out there?

**Comment by schneems** [comment]
Not totally sure what you mean. The issue auto closes when the PR is merged.

**Comment by Schwad** [comment]
@schneems this was emailed to me, via code triage, as an open issue after the PR was merged.

**Comment by Schwad** [comment]
My day to day workflow is gitlab so I wasn't sure whether an issue could be merged and open (which it can in gitlab). I was just operating off what I was served with the CodeTriage notification.

**Comment by lostapathy** [comment]
Clearly the issue on #525 just hates things I've worked on :)

**Pull request merged**
