### PR TITLE
Added Stars Count Feature

### PR DESCRIPTION
**Pull request by SagareGanesh**
#502 Added feature to display stars of repository on main page. See Demo
codetriage2

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
This looks good, but the alignment is broken? Any way to fix this?

Also instead of rake task, you can add code to update the stars count in the migration for adding the stars_count column itself. We will delete that part later when the migration is run in production.

**Comment by SagareGanesh** [comment]
Hi @prathamesh-sonpatki I have added a migration to update `stars_count` of Repos. Also Fixed alignment issue. Now main page looks like
code_triage1

Thanks.

**Comment by SagareGanesh** [comment]
@prathamesh-sonpatki  All test cases passed locally. see 
![test_cases_codetriage](https://cloud.githubusercontent.com/assets/16730632/18029022/ef1b428c-6ca9-11e6-9b61-f48c0a5e483d.png
I don't know why test cases failed here. am I missing something here?

**Comment by prathamesh-sonpatki** [comment]
@SagareGanesh Can you align starts count and issues counts to the left side? It looks a bit weird to me on right hand side :smile:

@schneems :+1: for this?

**Comment by SagareGanesh** [comment]
hi @prathamesh-sonpatki  I have updated alignment of _**`Stars Count`**_ and _**`Issues Count`**_  of Repos. Now _**Main**_ page looks like codetriage1 Thanks.

**Pull request merged**
