### PR TITLE
.editorconfig to make a default indenting style

### PR DESCRIPTION
**Pull request by marceloboeira**
I've noticed recently that a lot of pull requests are getting dirty because of the different coding style of all contributors, so a way to try to get this to work is editorconfig. The contributors just need a plugin on their default Code Editor. 
Please check their website: http://editorconfig.org

### CODE REVIEW

**Comment by axlos** [comment]
@marceloboeira Recently I had been thinking about that, because I didn't know what code style carry out, thanks for sharing it.

**Comment by schneems** [comment]
I'm fine with this, anyone else want to comment?

**Comment by prathamesh-sonpatki** [comment]
:+1:

**Comment by marceloboeira** [comment]
:smile:

**Pull request merged**
