### PR TITLE
Introduce help page

### PR DESCRIPTION
**Pull request by cheerfulstoic**
I was having trouble finding the original instructions that I received on how to triage.  This pull request:
- Makes a new section with those instructions
- Uses the same partial to render the instructions in the intro E-Mail
- Links to the help page from the daily E-Mails

I tried making the "_guide_to_triage" partial be a markdown file so that it could be both HTML and plain text like in the E-Mail templates, but I wasn't sure how to do that

This should address #337

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Does this seem good?  Somebody on holiday? ;)

**Comment by schneems** [comment]
My github notifications were all going to trash. Sorry :(

**Comment by cheerfulstoic** [comment]
No problem!  I know it's not easy running an OSS project ;)

**Comment by cheerfulstoic** [comment]
By the way, so far I've been using this project just on my own projects which have a decent backlog of issues.  Our previous strategy was going through issues every once in a while to clean up.  It's great having issues sent to me daily so that I can work through them at a manageable pace.  You might want to market it as a tool for that as well.

**Comment by schneems** [comment]
Thanks, that's good to hear. I've had some features requested to make this better for projects you own. For example a "week in review" of all issues opened and not closed this week. Also probably some kind of either a stale issue notifier or bot. 

Sorry about the delay on getting this merged in, we went through a whirlwind of changes. When I got this patch to apply cleanly it needed some styles. Then I wasn't sure about some stuff. Right now it sits in a branch on my local machine. It will probably be a bit more time before i'll be able to come back to this.

**Comment by schneems** [comment]
> You might want to market it as a tool for that as well.

I forgot to ask. Do you have any ideas how individual project owners might want to be targeted? What would a good way to reach out be?

**Comment by cheerfulstoic** [comment]
No problem, take your time ;)

As to reaching out to project owners, my main thought was just listing it as another use-case on the homepage (which looks great, BTW).  Perhaps when people sign-in with GitHub you could scan their repos and point out ones with a lot of issues (perhaps prioritized by how recently they've been updated)

**Comment by nateberkopec** [comment]
@cheerfulstoic Can you rebase this? I'd like to see it live on a review app.

**Comment by cheerfulstoic** [comment]
Sorry, I'm insanely busy lately, but the changes should be pretty easy to copy into master.  I don't care if they're your commits ;)

**Pull request closed without merging**
