### PR TITLE
Upgrade to Rails 5.2.0

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
There is one failure happening locally:

```
Failure:
PagesControllerTest#test_cache_control_for_headers [/Users/prathamesh/Projects/sources/codetriage/test/functional/pages_controller_test.rb:25]:
--- expected
+++ actual
@@ -1 +1 @@
-"no-cache, no-store, max-age=0, must-revalidate"
+"no-cache, no-store"
```

**Comment by schneems** [comment]
For that failure. We are manually setting headers in the pages controller in a method. I’m not quite sure why.

**Comment by prathamesh-sonpatki** [comment]
The failure is due to changes in this PR https://github.com/rails/rails/pull/30367

I think we will need to modify the test as that commit streamlines the behaviour of setting cache control headers. I didn't understand that code completely yet, once I do, I will update the test.

**Comment by prathamesh-sonpatki** [comment]
Didn't get time to look into this and now we are on RC2 :smile: Will try to wrap it up in next few days.

**Comment by schneems** [comment]
Let me know if you need anything

**Comment by prathamesh-sonpatki** [comment]
@schneems Ready to review!

**Comment by schneems** [comment]
Looks good. I did ask one question. After that’s sorted out it should be good to merge.

**Comment by prathamesh-sonpatki** [comment]
@schneems Done, please check

**Comment by schneems** [comment]
Thanks!

**Comment by schneems** [comment]
Thanks!

**Pull request merged**
