### PR TITLE
Remove missing closing tag

### PR DESCRIPTION
**Pull request by igas**

### CODE REVIEW

**Comment by igas** [comment]
Also would you mind @schneems @prathamesh-sonpatki if I change layouts from sequential where open/closing tags in different partials, like open `<body>` in `_head` and closing `</body>` in `_footer` to something more semantical like entire `<head>` to something like `_meta` and all flash stuff to `_flashes`? I think it'll be cleaner and editors stop alerting inconsistent markups etc

**Comment by prathamesh-sonpatki** [comment]
@igas Thanks :+1: . I guess changing layouts will be fine to make it consistent :)

**Comment by schneems** [comment]
Thanks :heart: 

That change sounds like a good one :+1:

**Comment by arthurnn** [comment]
HAML ! =)

**Comment by igas** [comment]
@arthurnn :smile: I personally prefer slim, but erb was here originally. I started global refactoring of views, first pr #323 about layouts. We can discuss changing of template language and prevent double work. /cc @schneems @prathamesh-sonpatki

**Comment by schneems** [comment]
I have nothing against slim, i've heard great things about it.

For HAML...i've used it, and i'm mostly :-1: the idea (indentation sensitive templates) however I'm not in love with the syntax

**Pull request merged**
