### PR TITLE
Remove :registerable from User devise modules

### PR DESCRIPTION
**Pull request by foxycoder**
Fixes codetriage/codetriage#580

### CODE REVIEW

**Comment by schneems** [comment]
One test is failing

```
UserSessionTest#test_sign_in_screen_renders [/home/travis/build/codetriage/codetriage/test/integration/user_session_test.rb:6]:
Expected false to be truthy.
```

**Comment by schneems** [comment]
One test is failing

```
Failure:
UserSessionTest#test_sign_in_screen_renders [/home/travis/build/codetriage/codetriage/test/integration/user_session_test.rb:6]:
Expected false to be truthy.
bin/rails test test/integration/user_session_test.rb:4
```

**Comment by foxycoder** [comment]
Flickering, apparently.

I ran it a bunch of times locally until it failed, then reused the seed to fix the bug in the test by specifically logging out the user before each test.

Hope it doesn't fail again on that email frequency test that also flickers.

**Comment by foxycoder** [comment]
🎉

**Comment by schneems** [comment]
Getting a ton of failures on heroku, I think it's their (our) fault though. So i'll take it up with them (me/us).

```
       WARNING: Rails was not able to disable referential integrity.
       This is most likely caused due to missing permissions.
       Rails needs superuser privileges to disable referential integrity.
       cause: PG::InsufficientPrivilege: ERROR:  permission denied: "RI_ConstraintTrigger_a_14215290" is a system trigger
       : ALTER TABLE "data_dumps" DISABLE TRIGGER ALL;ALTER TABLE "doc_assignments" DISABLE TRIGGER ALL;ALTER TABLE "doc_classes" DISABLE TRIGGER ALL;ALTER TABLE "doc_comments" DISABLE TRIGGER ALL;ALTER TABLE "doc_methods" DISABLE TRIGGER ALL;ALTER TABLE "issue_assignments" DISABLE TRIGGER ALL;ALTER TABLE "issues" DISABLE TRIGGER ALL;ALTER TABLE "opro_auth_grants" DISABLE TRIGGER ALL;ALTER TABLE "opro_client_apps" DISABLE TRIGGER ALL;ALTER TABLE "repos" DISABLE TRIGGER ALL;ALTER TABLE "users" DISABLE TRIGGER ALL;ALTER TABLE "repo_subscriptions" DISABLE TRIGGER ALL;ALTER TABLE "schema_migrations" DISABLE TRIGGER ALL;ALTER TABLE "ar_internal_metadata" DISABLE TRIGGER ALL
       E
       Error:
       UserTest#test_valid_email?_is_true_when_valid:
       ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "repo_subscriptions" violates foreign key constraint "fk_rails_9c589b2801"
       DETAIL:  Key (repo_id)=(915227508) is not present in table "repos".
       : INSERT INTO "repo_subscriptions" ("created_at", "updated_at", "last_sent_at", "email_limit", "id", "repo_id", "user_id") VALUES ('2013-10-29 21:09:48.351554', '2013-10-29 21:09:48.351554', NULL, 3, 972225963, 915227508, 616390896)
       
       bin/rails test test/unit/user_test.rb:32
```

**Comment by nateberkopec** [comment]
I think I mentioned this to you on Slack, @schneems, but I think codetriage needs its database version upgraded Postgres 9.4+ or something like that.

**Pull request merged**
