### PR TITLE
upgraded to rails 4.2.5

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@ferdinandrosario Thanks for the PR. Can you please update the code to only upgrade Rails. I think the build broke because `puma_auto_tune` gem also got updated which we don't want to upgrade :smile:

**Comment by ferdinandrosario** [comment]
@prathamesh-sonpatki Done :+1:

**Comment by prathamesh-sonpatki** [comment]
@ferdinandrosario Awesome. Can you check why one of the test is failing?

**Comment by ferdinandrosario** [comment]
Sure @prathamesh-sonpatki

**Comment by hamitron** [comment]
Looks like this is the failure:
`IssueTest#test_issue_counter_cache [/home/travis/build/codetriage/codetriage/test/unit/issue_test.rb:20]:
"Repo.find(603590727).issues_count" didn't change by -1.
Expected: 0
  Actual: 1
`

**Comment by schneems** [comment]
I also changed a ton of stuff on master, this will need a rebase. We merged the new view styles in! I'm working on some performance stuff. Right now the site is barely able to load due to us not limiting repo size via pagination etc, i'm working on it.

**Comment by prathamesh-sonpatki** [comment]
@ferdinandrosario Thanks :smile:

**Comment by schneems** [comment]
Thanks for this! BTW I added a perf regression back in so I could test out some memory profiling tools https://github.com/codetriage/codetriage/commit/9543d901e394fe9dc30d7061b0e265e7df6057a0 it doesn't impact performance that much. I'll take it out when i'm done. Wanted to mention this was intentional so no one accidentally "fixed" it. Thanks again!

**Pull request merged**
