### PR TITLE
Schneems/rails 6

### PR DESCRIPTION
**Pull request by schneems**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by schneems** [comment]
We're getting a few deprecation warnings that are likely coming from gems 

```
........DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (2 levels) in <class:RepoSubscriptionsControllerTest> at /Users/rschneeman/Documents/projects/codetriage/test/functional/repo_subscriptions_controller_test.rb:28)
```

These are probably actually ours:

```
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1 (please, use update instead) (called from update at /Users/rschneeman/Documents/projects/codetriage/app/controllers/users_controller.rb:25)
.DEPRECATION WARNING: update_attributes! is deprecated and will be removed from Rails 6.1 (please, use update! instead) (called from authenticate at /Users/rschneeman/Documents/projects/codetriage/app/services/git_hub_authenticator.rb:15)
```

**Comment by prathamesh-sonpatki** [comment]
We can merge #922 with this change. I will take a look at combining those two PRs

**Comment by schneems** [comment]
> I will take a look at combining those two PRs 

Awesome, thanks!

**Comment by prathamesh-sonpatki** [comment]
@schneems Build is now green, only deprecation warnings are remaining

**Pull request merged**
