### PR TITLE
Upgrade Ruby

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by schneems** [comment]
Getting an error in CI? 

```
       NoMethodError: undefined method `[]' for nil:NilClass

       An error occurred while installing puma (3.11.4), and Bundler cannot continue.

       Make sure that `gem install puma -v '3.11.4'` succeeds before bundling.

       

       In Gemfile:

         puma

 !

 !     Failed to install gems via Bundler.
```

**Comment by prathamesh-sonpatki** [comment]
@schneems Is it happening on Heroku CI? Can you give me access to it?

**Comment by schneems** [comment]
@prathamesh-sonpatki you should have access under your github email address. Are you using another email address with Heroku?

**Comment by prathamesh-sonpatki** [comment]
I can see it now

**Pull request closed without merging**
