### PR TITLE
Add initial rubocop config

### PR DESCRIPTION
**Pull request by benoittgt**
Hello

As mention in #606. Here is the initial commit for rubocop. I added the todo list of offenses. We still have to choose which "cops" we enable and sometimes at which level.

This PR rely on #607 otherwise I was not able to build the app.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Merci! Does that Travis CI output look right to you? It doesn't look like it's only running on changed files.

**Comment by schneems** [comment]
I'm not an expert here. Tests are passing. Good to merge?

**Comment by nateberkopec** [comment]
Hold up, @benoittgt added something that was supposed to only run rubocop on changed files I think but it doesnt appear to work. Wanna hear his reply first.

I am also OK with just running Travis on all files every build.

**Comment by benoittgt** [comment]
Yes. I don't seem that Travis is impacted about the result of rubocop. I'm gonna have a look.

**Comment by benoittgt** [comment]
Ok it works for Travis. If I run on all files I have two offenses that's why the CI failed.

**Comment by nateberkopec** [comment]
Cool, fix 'em and lets merge this.

**Comment by benoittgt** [comment]
I was able to fix one. But the one in `config/environments/production.rb:89` was a mystery for me.

I tried
```ruby
  config.cache_store = if ENV["MEMCACHIER_SERVERS"]
                         :dalli_store,
                           (ENV["MEMCACHIER_SERVERS"] || "").split(","),
                           {:username => ENV["MEMCACHIER_USERNAME"],
                            :password => ENV["MEMCACHIER_PASSWORD"],
                            :failover => true,
                            :socket_timeout => 1.5,
                            :socket_failure_delay => 0.2
                         }
                       else
                         :dalli_store
                       end
```

But
```
/Users/bti/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': /Users/bti/code/codetriage/config/environments/production.rb:90: syntax error, unexpected ',', expecting keyword_end (SyntaxError)
                 :dalli_store, (ENV["MEMCACHIER_SERVERS"] ||
```

So it's disabled for this part. If you have a solution I will change it.

**Comment by nateberkopec** [comment]
Good enough 👍  Thanks @benoittgt!

**Pull request merged**
