### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by schneems**
Badges allow visitors to see at a glance how many people are subscribed to your project and, the "status" of issues. For now this is a hard coded value based on the number of issues, but we could change it to a ratio or something else more clever.

I worry that larger projects would shy away from putting a red badge on their repo, but then again maybe it would encourage them to keep issue counts low. Curious on other's thoughts here. Ideally a green badge should be a point of pride.

Here is a screen shot:

When you click the badge you get a modal prompting you to copy the image url/markdown/etc.

### CODE REVIEW

**Comment by schneems** [comment]
@kylefiedler if you have a second could you take a look at this modal concept and badge? Don't want to mangle all the great work you did :grinning: I understand if you don't have time.

**Comment by kylefiedler** [comment]
@schneems I can probably get to it next week. If you want ship it and I can add the styles then. Or if you don't mind waiting I'll have them in by next Friday.

**Comment by schneems** [comment]
I can wait. Thanks!

**Comment by schneems** [comment]
I set up review apps for this repo, now on every PR you'll get a Heroku app deployed. Here's this one https://codetriage-staging-pr-414.herokuapp.com/schneems/wicked

**Pull request merged**
