### PR TITLE
bootscale -> bootsnap, close #549

### LINKED ISSUE #549: Bootscale -> Bootsnap

### PR DESCRIPTION
**Pull request by nateberkopec**
Bootsnap
real	0m1.290s
user	0m1.088s
sys	0m0.181s

Bootscale
real	0m2.083s
user	0m1.812s
sys	0m0.238s

Base
real	0m3.065s
user	0m2.177s
sys	0m0.839s

### CODE REVIEW

**Comment by nateberkopec** [comment]
Linking https://github.com/Shopify/bootsnap/issues/34#issuecomment-304463735

**Comment by schneems** [comment]
According to @rafaelfranca you can use both bootsnap and bootscale together.

**Comment by nateberkopec** [comment]
I tried and got a stack-too-deep error.

**Comment by nateberkopec** [comment]
Added a hacked rakefile, seems to work in tests now.

**Comment by rafaelfranca** [comment]
oh! Sorry, what I meant to say is that you can use spring and bootsnap together since they are complementary. Bootsnap is a evolution of bootscale so they may break if used together since they do similar monkey patches.

**Comment by nateberkopec** [comment]
OK, if this passes CI I think it's good to go.

**Comment by schneems** [comment]
Thanks @nateberkopec for this PR and thanks @rafaelfranca for the clarification. Thanks Shopify and @burke for the library. This is awesome!

**Comment by nateberkopec** [comment]
It really is incredibly snappy. Super impressive.

**Pull request merged**
