### PR TITLE
Add difficulty level tracking to Issues

### PR DESCRIPTION
**Pull request by mjc**
**This is a work in progress.**

I'm sending the pull request now to measure interest and gather feedback.

The idea is to allow anyone who can comment on an issue to comment
with a tag in the comment body that can inform CodeTriage of the
difficulty level of a particular issue.

The idea is that CodeTriage users should be able to select what
difficulty level(s) they are interested in, making CodeTriage
more useful for beginners and those who only feel comfortable
adding documentation.

Currently it uses whatever tag is last added to the comments.
This may not be the optimal method of picking tags.

Open questions:
- What levels are appropriate?
- Are multiple levels desired, (say "expert" and "documentation")?
- Is "codetriage-foo" a reasonable tag format or should something else be used?

I'm sure there are other things to discuss about this as well.

Feedback encouraged. :)

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
+1 terrific idea! I am trying to remember where I saw some good work on this, to model. There was something like a 'newbies-task' tag I saw.
AnneTheAgile

**Comment by jroes** [comment]
Hey @mjc can you rebase this change with master?

**Comment by AnneTheAgile** [comment]
@jroes, is there any way to see the merge conflicts here on the web? or would I need to check it out and do the trial merge/rebase myself?

I had this question on a few projects. 
Here I checked and the version of the rb schema is the same; https://github.com/codetriage/codetriage/search?utf8=%E2%9C%93&q=20140710164307
So at least that part isn't the issue :)

I had a related idea this morning. I'd like to rate how easy it is to contribute to repos. Saltstack is amazing. They appreciate every tiny thing I do for them and really encourage me to help. It's truly inspiring! I'd like to give them a +1 through triage to alert others how easy a place it is to start.

**Comment by nateberkopec** [comment]
Stale, feel free to reopen.

**Pull request closed without merging**
