### PR TITLE
Rails 5.1.3

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by schneems** [comment]
```
rake aborted!
NoMethodError: undefined method `rake_run' for Minitest:Module
/home/travis/build/codetriage/codetriage/Rakefile:46:in `block in <main>'
```

**Comment by prathamesh-sonpatki** [comment]
Will look into this failure 😅

**Comment by prathamesh-sonpatki** [comment]
The test suite got stuck for me.

``` sh
$ bin/rails test
I, [2017-09-07T12:51:04.181666 #57865]  INFO -- : Loaded Configuration: /Users/prathamesh/Projects/sources/codetriage/config/scout_apm.yml. Using environment: test
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <main> at /Users/prathamesh/Projects/sources/codetriage/config/initializers/new_framework_defaults.rb:22)
Run options: --seed 31767

# Running:

......................................................F

Failure:
EmailRateLimitTest#test_decides_daily_email_frequency [/Users/prathamesh/Projects/sources/codetriage/test/unit/email_rate_limit_test.rb:17]:
Expected  EmailRateLimit.new(3, minimum_frequency: 'once_a_week').now?(28) to be false, was not


bin/rails test test/unit/email_rate_limit_test.rb:8

.........................................................
```

Has anyone seen this before?

**Comment by schneems** [comment]
That tests for a range of conditions and on some of them it fails. Since it's randomly generating the values it only randomly fails. 

I've looked at the logic and can't figure out what is messed up.

**Comment by prathamesh-sonpatki** [comment]
Ok, it failed for me twice, will take a look

**Comment by prathamesh-sonpatki** [comment]
Closing in favor of #631

**Pull request closed without merging**
