### PR TITLE
First batch of "Fix rubocop offenses"

### PR DESCRIPTION
**Pull request by benoittgt**
Hello

Here is the first batch of style corrections. 

Prefer this link to review changes: https://github.com/codetriage/codetriage/pull/610/files?w=1 
It will no display whitespace changes.

### CODE REVIEW

**Comment by benoittgt** [comment]
Closing and reopening the PR because CI failed for an offense I fixed.

**Comment by schneems** [comment]
I'm still seeing one failure on travis

**Comment by benoittgt** [comment]
I've tried many things and open an issue on rubocop : https://github.com/bbatsov/rubocop/issues/4657

**Comment by benoittgt** [comment]
I rely too much on autogenerated todolist. I will close this PR and start a new one after discussing with @palkan.

**Pull request closed without merging**
