### PR TITLE
Language subscription

### PR DESCRIPTION
**Pull request by jacarandang**
Based on #131
I haven't done the actual sending of email but I can already select a random issue from a random repo in that language. However, my algorithm doesn't check if there is a repo with an issue in the current language subscription so it will try to find an issue from every repo in that language which yields to a lot of queries being executed.

TODO:
Adding language sunbscription to the daily triage email
Improve relationship between models
Email limit for language subscription
Tests

I'm also thinking of automatically subscribing the user to their favorite language.

### CODE REVIEW

**Comment by jacarandang** [comment]
Finally, the issues from language subscription is added to the daily triage emails. However it doesn't follow the daily issue limit the user sets. I'm thinking of adding issue limit for each language subscription. Code is still messy and no test done yet.

**Comment by jacarandang** [comment]
When subscribing
ls1

ls2

Email sent on subscription
ls3

Daily Triage Email
ls4

**Comment by jacarandang** [comment]
Email limit for each language implemented. Code is still messy and randomizer is still slow. No tests yet

**Comment by jacarandang** [comment]
Created test for this feature.

**Comment by jacarandang** [comment]
Hi, I tried working on this feature at #361. It's mostly done and with some test. Any thoughts? @schneems

**Comment by nateberkopec** [comment]
Stale, feel free to reopen.

**Pull request closed without merging**
