### PR TITLE
Bump Rails to 5.2.1

### PR DESCRIPTION
**Pull request by greysteil**
Full Rails 5.2.1 release was released yesterday. 🎉

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Thanks 👍

**Comment by greysteil** [comment]
You're very welcome.

Would you be up for automating dependency updates with [Dependabot](https://dependabot.com)? I think it would save you a bit of time and help keep codetriage up-to-date, but I also have a bigger plan for it: I'm keen to get more open source apps using it so I can use the data on the CI runs for dependency updates to find bugs in new releases and point the maintainers to the failing CI run as a reproduction step.

What do you reckon?

**Comment by schneems** [comment]
Can’t hurt. Do we need to sign up for it or enable in some way?

**Comment by greysteil** [comment]
❤️ 

Yeah - just add it from [here](https://github.com/apps/dependabot) and then add codetriage once you get through to http://app.dependabot.com.

Let me know if you have any trouble / feedback at all.

**Comment by schneems** [comment]
I added codetriage/codetriage

**Pull request merged**
