### PR TITLE
Collection caching is now explicit, does not happen automatically

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- This change was made in https://github.com/rails/rails/pull/23695.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Updated as per http://edgeguides.rubyonrails.org/caching_with_rails.html#collection-caching.

**Comment by prathamesh-sonpatki** [comment]
Opened issue https://github.com/rails/rails/issues/24132 regarding the test failures.

**Comment by schneems** [comment]
Thanks for the report

**Comment by prathamesh-sonpatki** [comment]
Seems to be related to rails-controller-testing gem. Investigating more.

**Comment by prathamesh-sonpatki** [comment]
@schneems This can be merged after merging PR about Rails 5.0 beta4. It has a fix for test failures.

**Pull request merged**
