### PR TITLE
Add Search for repo on CodeTriage. #306

### PR DESCRIPTION
**Pull request by axlos**
Hello Team!

This pull request is referent to improvement No. #306. I developed a component to find repos both as description as name. I look for local registers using jquery.

### CODE REVIEW

**Comment by marceloboeira** [comment]
:+1:

**Comment by schneems** [comment]
This looks really cool. Is there any way to test this? We have some other javascript tested with teacup i believe. Maybe a phantomjs integration test would work?

**Comment by marceloboeira** [comment]
@axlos if you need some help to test this just let me know

**Comment by axlos** [comment]
Ok guys I'm going to use Phantomjs to test it, what do you think?

**Comment by marceloboeira** [comment]
@axlos you can write a test that simulate the functionality, it access the page, writes something on the search input and then check the answer list  to be exactly the expected.

**Comment by axlos** [comment]
Hi codetriage team,

I realize that codetriage project has been using "Teaspoon" as a Javascript test runner and "Mocha", as a javascript testing framework.

I also know that every javascript or coffeescript inside the folder test/javascript will be executed automatically.

But I've got a little problem, I couldn't integrate PhantomJS in an javascript test, I don't know why It can't  recognize it.

"Teaspoon will use PhantomJS by default." [Using PhantomJS](https://github.com/modeset/teaspoon/wiki/Using-PhantomJS)

**Comment by prathamesh-sonpatki** [comment]
@axlos Can you post the error that you are getting? Also if you push the code that will be even better. So that we can test on our machines also.

Thanks for picking this up :+1:

**Comment by chrisccerami** [comment]
@axlos Just noticed it's been a few months since your last comment. Any luck with testing this? Would you be able to push the code you have so far or post your error?

**Comment by gizotti** [comment]
@schneems 

Is this something that people would still want? I am keen pick this one up if @axlos doesn't plan to keep going.

**Comment by nateberkopec** [comment]
Stale, feel free to reopen.

**Pull request closed without merging**
