### PR TITLE
Fix teaspoon warnings on bootup

### PR DESCRIPTION
**Pull request by tejasbubane**
heroku local generated warnings from teaspoon since the teaspoon config options changed slightly.

Here are the warnings on master:

```
1:49:00 PM web.1    |  WARNING: Deprecated - Teaspoon.setup is deprecated, use Teaspoon.configure instead. The /initializer/teaspoon.rb file should be removed, and a new teaspoon_env.rb file should be created by running the install generator.
1:49:00 PM web.1    |  WARNING: Deprecated - the teaspoon fixture_path directive has been changed to fixture_paths, which expects an array, please update your configuration.
1:49:00 PM web.1    |  WARNING: Deprecated - suite.no_coverage has been removed in Teaspoon 1.0. Please use coverage.ignore instead. https://github.com/modeset/teaspoon/blob/master/CHANGELOG.md
1:49:00 PM worker.1 |  WARNING: Deprecated - Teaspoon.setup is deprecated, use Teaspoon.configure instead. The /initializer/teaspoon.rb file should be removed, and a new teaspoon_env.rb file should be created by running the install generator.
1:49:00 PM worker.1 |  WARNING: Deprecated - the teaspoon fixture_path directive has been changed to fixture_paths, which expects an array, please update your configuration.
1:49:00 PM worker.1 |  WARNING: Deprecated - suite.no_coverage has been removed in Teaspoon 1.0. Please use coverage.ignore instead. https://github.com/modeset/teaspoon/blob/master/CHANGELOG.md
```

### CODE REVIEW

**Comment by tejasbubane** [comment]
Also fixed the circular reference warnings:

```
1:49:01 PM worker.1 |  /Users/tejas/opensource/codetriage/app/helpers/repos_helper.rb:2: warning: circular argument reference - text
1:49:01 PM worker.1 |  /Users/tejas/opensource/codetriage/app/helpers/repos_helper.rb:2: warning: circular argument reference - path
```

**Comment by prathamesh-sonpatki** [comment]
Looks good. Are teaspoon tests working now? I remember we commented them when upgraded to Rails 5.

**Comment by tejasbubane** [comment]
@prathamesh-sonpatki Yep. They are commented [here](https://github.com/codetriage/codetriage/blob/master/lib/tasks/test.rake). Uncommenting them leads to this failure:

```
Teaspoon running default suite at http://127.0.0.1:65187/jstest/default
Error: ActionView::Template::Error: couldn't find file 'application' with type 'text/coffeescript'
/Users/tejas/opensource/codetriage/test/javascript/js_test_helper.coffee:1
```

**Comment by prathamesh-sonpatki** [comment]
Ok. we will tackle them later :smile:

Thanks for this cleaning up!

**Comment by prathamesh-sonpatki** [comment]
500th PR 💯

**Comment by schneems** [comment]
🎉🎉🎉

**Comment by schneems** [comment]
Teaspoon is really far behind the active version, upgrading it will be a huge task :(

**Pull request merged**
