### PR TITLE
Replace aws-sdk in favor of aws-sdk-s3

### PR DESCRIPTION
**Pull request by lucianosousa**
There is no need to use all of these dependencies, since we already have this modular S3 gem

### CODE REVIEW

**Comment by lucianosousa** [comment]
@schneems any interest in merge this? I can rebase if you want to

**Comment by schneems** [comment]
Apparently I can’t re-open a PR if the branch is deleted. Can you in-delete it? It’s a good change.

**Comment by lucianosousa** [comment]
@schneems done

**Comment by lucianosousa** [comment]
@schneems rebased with current master

**Comment by schneems** [comment]
Sorry for the delay. Thanks for the patch!

**Pull request merged**
