### PR TITLE
 Bump to Rails 4.2.1

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
//cc @schneems @arthurnn

**Comment by arthurnn** [comment]
:tada: ! :ship:

**Comment by schneems** [comment]
It looks like this change dropped our RAM useage dramatically, i don't know why.

## Before


## After


Notice we're not swapping anymore

**Comment by prathamesh-sonpatki** [comment]
Could this be related to our switch to Ruby 2.2.1?

**Comment by schneems** [comment]
Maybe, however Ruby 2.2.1 was deployed a LONG time ago, I took that "before" screenshot pretty recently.  Maybe it's the combination of 2.2.1 and Rails 4.2.1 or something. :shrug:

**Comment by schneems** [comment]
Looks like it's 2 things, I was playing with GC settings and i set `RUBY_GC_HEAP_GROWTH_FACTOR=1.1` which when reverted brings back the memory errors. I had this set before and we were throwing errors, so It's probably the combination of this and Rails 4.2.1.

I may try to revert to reproduce the memory issues to confirm. While i'm glad the issue is fixed, I wish I knew why it happened in the first place or nothing is stopping the issue from mysteriously coming back.

**Comment by schneems** [comment]
If I rollback to v389 which corresponds to this commit: https://github.com/codetriage/codetriage/commit/6a13453 the memory problems come back. 

If I rollback to v390 which corresponds to https://github.com/codetriage/codetriage/commit/13f3f1e then the memory problems go away. So something definitely helped bring down memory when we went from the RC to the release, not sure what it was. I cannot reproduce the memory growth locally, only on production. I'm going to look into heap dumping sometime this week:

**Comment by schneems** [comment]
Here's the diff between the RC and official release https://github.com/rails/rails/compare/v4.2.1.rc3...v4.2.1

I don't see anything that would help with memory. Maybe it's due to another dependent gem being updated.

**Pull request merged**
