### PR TITLE
Updated for Rails 4.2.3

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@ferdinandrosario Thanks :smile: May be you ran `bundle update` so lots of gems got updated.

Can you do only `bundle update rails` so that we will not get all the other gems updated.

**Comment by ferdinandrosario** [comment]
Done :+1:  hope the build will pass now :smile:

**Comment by prathamesh-sonpatki** [comment]
Perfect :+1:

**Comment by schneems** [comment]
Thanks everyone!

**Pull request merged**
