### PR TITLE
Fixed page crash on duplicate repo

### PR DESCRIPTION
**Pull request by chrisccerami**
Previously when submitting a repo that had already been added, the page would crash. It now correctly renders the page with error messages. #335

### CODE REVIEW

**Comment by schneems** [comment]
The error we're seeing:

```
 undefined method `errors' for nil:NilClass
```

This looks like `@repo_sub` is unexpectedly nil. This is happening because the `new` method does not assign a `@repo_sub` variable. To fix we can add `@repo_sub = RepoSubscription.new` in `def new`

**Comment by chrisccerami** [comment]
I have fixed that error in my local version, but I'm dealing with another error so I haven't pushed the change yet. I'll the post the error in a bit.

**Comment by schneems** [comment]
Looks like tests are passing now. You good to go here or you wanted me to wait?

**Comment by chrisccerami** [comment]
@schneems Yeah, should be good to merge. I created this PR as a branch off of 333, so once it gets merged I think that PR should be good to go as well.

**Comment by CjayBillones** [comment]
@chrisccerami does your error messages look just like this?

plain-error-message

This is what I fetched from you branch and if ever you haven't made any designs for it yet, I made it into something like this.

designed-error-message

**Comment by chrisccerami** [comment]
Those were the errors that were already there, I simply fixed the exception that was breaking the page.

**Comment by CjayBillones** [comment]
@chrisccerami Yes yes, I just wanted to confirm if you've done something on the UI of the error message (I might have missed it). :) Thanks!

@schneems @prathamesh-sonpatki I would like to know the status of this PR. I've fetched the fix applied by chris made some changes on the UI and fixed some other bugs that I have found once chris's PR is applied. Will it be fine if I submit my own PR including chris's fix on the exception for you guys to check?

**Pull request merged**
