### PR TITLE
Upgrade to Rails 5

### PR DESCRIPTION
**Pull request by schneems**
I picked off where #427 left off. There's a few more gems that needed to be updated and some minor code changes. 

I'm still getting some random failures that I think are omniauth related. Still investigating.

### CODE REVIEW

**Comment by schneems** [comment]
I'm getting this error locally too

```
ActionView::Template::Error: nil is not a valid asset source
    app/views/application/_nav.html.slim:9:in `_app_views_application__nav_html_slim__1550834241246068923_79168440'
    app/views/layouts/application.html.slim:7:in `_app_views_layouts_application_html_slim__587618798759587358_37113340'
    test/test_helper.rb:86:in `login_via_github'
    test/integration/maintaining_repo_subscriptions_test.rb:7:in `triage_the_sandbox'
    test/integration/maintaining_repo_subscriptions_test.rb:35:in `block in <class:MaintainingRepoSubscriptionsTest>'
```

This only happens when we're using the `login_via_github` test helper which uses the omniauth stubs. Sometimes `avatar_url` is nil, sometimes it isn't. I added logging and sometimes `current_user` is nil and sometimes it isn't. Really not sure where this is coming from.

**Comment by prathamesh-sonpatki** [comment]
I am getting a different failure on this branch -

```
F

Failure:
ReposControllerTest#test_trying_to_create_repo_without_logged_in_will_redirect_to_login_page:
Expected response to be a redirect to <http://test.host/users/auth/github?origin=%2Frepos%3Frepo%255Bname%255D%3Dcodetriage%26repo%255Buser_name%255D%3Dcodetriage> but was a redirect to <http://test.host/users/auth/github?origin=%2Frepos>.
Expected "http://test.host/users/auth/github?origin=%2Frepos%3Frepo%255Bname%255D%3Dcodetriage%26repo%255Buser_name%255D%3Dcodetriage" to be === "http://test.host/users/auth/github?origin=%2Frepos".
```

Investigating more.

**Comment by schneems** [comment]
Branch is green, I commented out teaspoon tests. We should revisit our javascript testing story. I have to run to a meeting. I'm fine to deploy and work on bugs when I get back.

**Comment by schneems** [comment]
Rails 5 beta is live on production

**Pull request merged**
