### PR TITLE
Major UI and UX suggested fixes

### PR DESCRIPTION
**Pull request by jacemonje**
Good day, me, @CjayBillones, and @jacarandang have collaborated on a project to improve and add features to CodeTriage UI (among other things) in the hopes that users would find using the site with a more streamlined experience. The tentative list of modifications are as follows:

-added a repo_path link
-made slimscroller for issues and projects so they dont take up the entire page
-made the fork ribbon fixed when scrolling
-still changing order of buttons so they wont be confusing to users
-and misc UI fixes

we will still be adding more as we go along. Thank you.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@jacemonje Thank you! Can you please post some screenshots of all changes? :smile:

**Comment by jacemonje** [comment]
screen shot 2015-06-17 at 11 40 27 am

Will add as we go along. @jacarandang has better snaps of the slimscroller feature

**Comment by jacarandang** [comment]
spheretoon3

This is for the slimscroller. We still have other changes in mind but this is our progress so far.

**Comment by jacemonje** [comment]
screen shot 2015-06-17 at 1 01 14 pm


^The Travis CI build failed because I lowercase'd a letter in a button

**Comment by jacemonje** [comment]
@prathamesh-sonpatki Are the changes satisfactory so far? Would love to get your insights!

**Comment by jacemonje** [comment]
@CjayBillones's modified repo listing :+1:  :100: 

screen shot 2015-06-19 at 9 56 33 am

screen shot 2015-06-19 at 9 56 40 am

**Comment by jacemonje** [comment]
@schneems Thoughts? :smile:

**Comment by prathamesh-sonpatki** [comment]
Thanks for this :smile: 
It's a bit big PR so hard to review :smile: Should we go page by page?

**Comment by jacemonje** [comment]
Sure! How do you want to go about it? :D would screenshots of every page do? My apologies, I'm a bit new to contributing and do not know best practices.

**Comment by prathamesh-sonpatki** [comment]
Yeah. One PR per page and then building on top of it.

**Comment by jacemonje** [comment]
@prathamesh-sonpatki First two of many PRs:

https://github.com/codetriage/codetriage/pull/367 (navbar) and https://github.com/codetriage/codetriage/pull/368 (slimscroller)

**Pull request closed without merging**
