### PR TITLE
Dropdown Select for Languages

### PR DESCRIPTION
**Pull request by CjayBillones**
Changed the tabbed pane for languages into a dropdown select. A specific language is just added in the options of the dropdown when that's the first repo with that language added.

screen shot 2015-06-23 at 10 34 04 am

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@CjayBillones Not sure but does it contain CSS fix or code fix?

**Comment by CjayBillones** [comment]
@prathamesh-sonpatki I haven't changed anything in the CSS. It's more of we just removed the tabbed-pane for languages and changed it into a dropdown instead.

**Comment by prathamesh-sonpatki** [comment]
Ok. I will defer to @schneems

**Comment by CjayBillones** [comment]
Thanks!

**Comment by prathamesh-sonpatki** [comment]
Closing this as we have new design now. Please feel free to open new issues with your suggestions.

Thanks for your help :smiley:

**Pull request closed without merging**
